-- MySQL Script generated by MySQL Workbench
-- 10/01/14 03:41:56
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario_administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario_administrador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario_administrador` (
  `rut` INT NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(20) NOT NULL,
  `mail` VARCHAR(25) NOT NULL,
  `contraseña` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`rut`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`malla`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`malla` ;

CREATE TABLE IF NOT EXISTS `mydb`.`malla` (
  `idMalla` VARCHAR(3) NOT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idMalla`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`descargas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`descargas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`descargas` (
  `idDescargas` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(200) NOT NULL,
  `url` VARCHAR(300) NOT NULL,
  `abstract` TEXT NOT NULL,
  `anio` DATE NOT NULL,
  `estado` INT NOT NULL,
  `usuario_administrador_rut` VARCHAR(45) NOT NULL,
  `usuario_administrador_rut1` INT NOT NULL,
  PRIMARY KEY (`idDescargas`),
  INDEX `fk_descargas_usuario_administrador1_idx` (`usuario_administrador_rut1` ASC),
  CONSTRAINT `fk_descargas_usuario_administrador1`
    FOREIGN KEY (`usuario_administrador_rut1`)
    REFERENCES `mydb`.`usuario_administrador` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`semestre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`semestre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`semestre` (
  `semestre` INT(2) NOT NULL,
  PRIMARY KEY (`semestre`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`asignatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`asignatura` ;

CREATE TABLE IF NOT EXISTS `mydb`.`asignatura` (
  `nombre` VARCHAR(200) NOT NULL,
  `codigo_malla` VARCHAR(3) NOT NULL,
  `numero` INT NOT NULL,
  `descrip` TEXT NOT NULL,
  `semestre_semestre` INT(2) NOT NULL,
  `malla_idMalla` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`nombre`),
  INDEX `fk_asignatura_semestre1_idx` (`semestre_semestre` ASC),
  INDEX `fk_asignatura_malla1_idx` (`malla_idMalla` ASC),
  CONSTRAINT `fk_asignatura_semestre1`
    FOREIGN KEY (`semestre_semestre`)
    REFERENCES `mydb`.`semestre` (`semestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignatura_malla1`
    FOREIGN KEY (`malla_idMalla`)
    REFERENCES `mydb`.`malla` (`idMalla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`mencion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`mencion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`mencion` (
  `idMencion` VARCHAR(3) NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `descrip` TEXT NOT NULL,
  `malla_idMalla` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`idMencion`),
  INDEX `fk_mencion_malla1_idx` (`malla_idMalla` ASC),
  CONSTRAINT `fk_mencion_malla1`
    FOREIGN KEY (`malla_idMalla`)
    REFERENCES `mydb`.`malla` (`idMalla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`asig_mencion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`asig_mencion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`asig_mencion` (
  `idCodigo` VARCHAR(6) NOT NULL,
  `especialidad` INT(1) NULL,
  `electivo` INT(1) NOT NULL,
  `profesor` VARCHAR(100) NOT NULL,
  `descripcion_corta` TEXT NOT NULL,
  `descripcion_larga` LONGTEXT NOT NULL,
  `url_imagen` VARCHAR(200) NOT NULL,
  `mencion_idMencion` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`idCodigo`),
  INDEX `fk_asig_mencion_mencion1_idx` (`mencion_idMencion` ASC),
  CONSTRAINT `fk_asig_mencion_mencion1`
    FOREIGN KEY (`mencion_idMencion`)
    REFERENCES `mydb`.`mencion` (`idMencion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`objetivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`objetivos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`objetivos` (
  `idObjetivo` INT(11) NOT NULL AUTO_INCREMENT,
  `idCodigo` VARCHAR(6) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `descrip` TEXT NOT NULL,
  `status` INT(1) NOT NULL,
  PRIMARY KEY (`idObjetivo`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Requisito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Requisito` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Requisito` (
  `Nombre_req` VARCHAR(200) NOT NULL,
  `cod_malla` VARCHAR(3) NOT NULL,
  `numero` INT NOT NULL,
  PRIMARY KEY (`Nombre_req`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`admin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `idAdmin` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `permiso` INT(2) NOT NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`asignaturas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`asignaturas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`asignaturas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `descrip` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`asig_codigo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`asig_codigo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`asig_codigo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo` INT(11) NOT NULL,
  `id_asig` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `codigo` (`codigo` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`asig_malla`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`asig_malla` ;

CREATE TABLE IF NOT EXISTS `mydb`.`asig_malla` (
  `id_malla` INT(11) NOT NULL,
  `id_semestre` INT(11) NOT NULL,
  `asignaturas` TEXT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`prerequisitos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`prerequisitos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`prerequisitos` (
  `idCodigo` INT(11) NOT NULL,
  `idPrereq` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`semestre_asig`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`semestre_asig` ;

CREATE TABLE IF NOT EXISTS `mydb`.`semestre_asig` (
  `idMatch` INT(11) NOT NULL AUTO_INCREMENT,
  `idMalla` INT(3) NOT NULL,
  `idCodigo` VARCHAR(6) NOT NULL,
  `semestre` INT(2) NOT NULL,
  PRIMARY KEY (`idMatch`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `rut` VARCHAR(12) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `asig_cursadas_json` TEXT NOT NULL,
  `malla` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`asignatura_has_objetivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`asignatura_has_objetivos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`asignatura_has_objetivos` (
  `asignatura_nombre` VARCHAR(200) NOT NULL,
  `objetivos_idObjetivo` INT(11) NOT NULL,
  PRIMARY KEY (`asignatura_nombre`, `objetivos_idObjetivo`),
  INDEX `fk_asignatura_has_objetivos_objetivos1_idx` (`objetivos_idObjetivo` ASC),
  INDEX `fk_asignatura_has_objetivos_asignatura1_idx` (`asignatura_nombre` ASC),
  CONSTRAINT `fk_asignatura_has_objetivos_asignatura1`
    FOREIGN KEY (`asignatura_nombre`)
    REFERENCES `mydb`.`asignatura` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignatura_has_objetivos_objetivos1`
    FOREIGN KEY (`objetivos_idObjetivo`)
    REFERENCES `mydb`.`objetivos` (`idObjetivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario_alumno` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario_alumno` (
  `rut` VARCHAR(45) NOT NULL,
  `nombre` INT NOT NULL,
  `nombre_malla` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rut`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`avance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`avance` ;

CREATE TABLE IF NOT EXISTS `mydb`.`avance` (
  `nombre` VARCHAR(200) NOT NULL,
  `codigo_malla` VARCHAR(3) NOT NULL,
  `numero` INT NOT NULL,
  `usuario_alumno_rut` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`),
  INDEX `fk_avance_usuario_alumno1_idx` (`usuario_alumno_rut` ASC),
  CONSTRAINT `fk_avance_usuario_alumno1`
    FOREIGN KEY (`usuario_alumno_rut`)
    REFERENCES `mydb`.`usuario_alumno` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`asignatura_has_Requisito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`asignatura_has_Requisito` ;

CREATE TABLE IF NOT EXISTS `mydb`.`asignatura_has_Requisito` (
  `asignatura_nombre` VARCHAR(200) NOT NULL,
  `Requisito_Nombre_req` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`asignatura_nombre`, `Requisito_Nombre_req`),
  INDEX `fk_asignatura_has_Requisito_Requisito1_idx` (`Requisito_Nombre_req` ASC),
  INDEX `fk_asignatura_has_Requisito_asignatura1_idx` (`asignatura_nombre` ASC),
  CONSTRAINT `fk_asignatura_has_Requisito_asignatura1`
    FOREIGN KEY (`asignatura_nombre`)
    REFERENCES `mydb`.`asignatura` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignatura_has_Requisito_Requisito1`
    FOREIGN KEY (`Requisito_Nombre_req`)
    REFERENCES `mydb`.`Requisito` (`Nombre_req`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`descargas_has_usuario_alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`descargas_has_usuario_alumno` ;

CREATE TABLE IF NOT EXISTS `mydb`.`descargas_has_usuario_alumno` (
  `descargas_idDescargas` INT(11) NOT NULL,
  `usuario_alumno_rut` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`descargas_idDescargas`, `usuario_alumno_rut`),
  INDEX `fk_descargas_has_usuario_alumno_usuario_alumno1_idx` (`usuario_alumno_rut` ASC),
  INDEX `fk_descargas_has_usuario_alumno_descargas1_idx` (`descargas_idDescargas` ASC),
  CONSTRAINT `fk_descargas_has_usuario_alumno_descargas1`
    FOREIGN KEY (`descargas_idDescargas`)
    REFERENCES `mydb`.`descargas` (`idDescargas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_descargas_has_usuario_alumno_usuario_alumno1`
    FOREIGN KEY (`usuario_alumno_rut`)
    REFERENCES `mydb`.`usuario_alumno` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`malla_has_semestre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`malla_has_semestre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`malla_has_semestre` (
  `malla_idMalla` VARCHAR(3) NOT NULL,
  `semestre_semestre` INT(2) NOT NULL,
  PRIMARY KEY (`malla_idMalla`, `semestre_semestre`),
  INDEX `fk_malla_has_semestre_semestre1_idx` (`semestre_semestre` ASC),
  INDEX `fk_malla_has_semestre_malla1_idx` (`malla_idMalla` ASC),
  CONSTRAINT `fk_malla_has_semestre_malla1`
    FOREIGN KEY (`malla_idMalla`)
    REFERENCES `mydb`.`malla` (`idMalla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_malla_has_semestre_semestre1`
    FOREIGN KEY (`semestre_semestre`)
    REFERENCES `mydb`.`semestre` (`semestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
