-- MySQL Script generated by MySQL Workbench
-- 11/26/14 00:11:03
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- -----------------------------------------------------
-- Schema tallerapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tallerapp` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`academico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`academico` (
  `idacademico` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `web` VARCHAR(100) NOT NULL,
  `fono` INT NOT NULL,
  `urlfoto` VARCHAR(100) NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`idacademico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`titulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`titulo` (
  `idtitulo` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `academico_idacademico` INT NOT NULL,
  PRIMARY KEY (`idtitulo`),
  INDEX `fk_titulo_academico_idx` (`academico_idacademico` ASC),
  CONSTRAINT `fk_titulo_academico`
    FOREIGN KEY (`academico_idacademico`)
    REFERENCES `mydb`.`academico` (`idacademico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`area_trabajo_academico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`area_trabajo_academico` (
  `idarea_trabajo_academico` INT NOT NULL AUTO_INCREMENT,
  `area` VARCHAR(45) NOT NULL,
  `academico_idacademico` INT NOT NULL,
  PRIMARY KEY (`idarea_trabajo_academico`),
  INDEX `fk_area_trabajo_academico_academico1_idx` (`academico_idacademico` ASC),
  CONSTRAINT `fk_area_trabajo_academico_academico1`
    FOREIGN KEY (`academico_idacademico`)
    REFERENCES `mydb`.`academico` (`idacademico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ayudante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ayudante` (
  `idayudante` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `periodo` INT NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `urlFoto` VARCHAR(100) NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`idayudante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`administrativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`administrativo` (
  `idadministrativo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `cargo` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `urlfoto` VARCHAR(100) NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`idadministrativo`))
ENGINE = InnoDB;

USE `tallerapp` ;

-- -----------------------------------------------------
-- Table `tallerapp`.`malla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallerapp`.`malla` (
  `idMalla` VARCHAR(3) NOT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idMalla`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tallerapp`.`semestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallerapp`.`semestre` (
  `semestre` INT(2) NOT NULL,
  PRIMARY KEY (`semestre`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tallerapp`.`asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallerapp`.`asignatura` (
  `id` INT(11) NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `numero` INT(11) NOT NULL,
  `descrip` TEXT NOT NULL,
  `semestre_semestre` INT(2) NOT NULL,
  `malla_idMalla` VARCHAR(3) NOT NULL,
  `profesor` VARCHAR(30) NOT NULL,
  `foto` VARCHAR(200) NOT NULL,
  `academico_idacademico` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_asignatura_semestre1_idx` (`semestre_semestre` ASC),
  INDEX `fk_asignatura_malla1_idx` (`malla_idMalla` ASC),
  INDEX `fk_asignatura_academico1_idx` (`academico_idacademico` ASC),
  CONSTRAINT `fk_asignatura_malla1`
    FOREIGN KEY (`malla_idMalla`)
    REFERENCES `tallerapp`.`malla` (`idMalla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignatura_semestre1`
    FOREIGN KEY (`semestre_semestre`)
    REFERENCES `tallerapp`.`semestre` (`semestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignatura_academico1`
    FOREIGN KEY (`academico_idacademico`)
    REFERENCES `mydb`.`academico` (`idacademico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tallerapp`.`objetivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallerapp`.`objetivos` (
  `idObjetivo` INT(11) NOT NULL AUTO_INCREMENT,
  `idCodigo_asig` VARCHAR(6) NOT NULL,
  `nombre_asig` VARCHAR(100) NOT NULL,
  `descrip` TEXT NOT NULL,
  `estado` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idObjetivo`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tallerapp`.`asignatura_has_objetivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallerapp`.`asignatura_has_objetivos` (
  `asignatura_id` INT(11) NOT NULL,
  `objetivos_idObjetivo` INT(11) NOT NULL,
  PRIMARY KEY (`asignatura_id`, `objetivos_idObjetivo`),
  INDEX `fk_asignatura_has_objetivos_objetivos1_idx` (`objetivos_idObjetivo` ASC),
  INDEX `fk_asignatura_has_objetivos_asignatura1_idx` (`asignatura_id` ASC),
  CONSTRAINT `fk_asignatura_has_objetivos_asignatura1`
    FOREIGN KEY (`asignatura_id`)
    REFERENCES `tallerapp`.`asignatura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignatura_has_objetivos_objetivos1`
    FOREIGN KEY (`objetivos_idObjetivo`)
    REFERENCES `tallerapp`.`objetivos` (`idObjetivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tallerapp`.`requisito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallerapp`.`requisito` (
  `cod_malla` VARCHAR(6) NOT NULL,
  `numero` INT(3) NOT NULL,
  PRIMARY KEY (`cod_malla`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tallerapp`.`asignatura_has_requisito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallerapp`.`asignatura_has_requisito` (
  `asignatura_id` INT(11) NOT NULL,
  `requisito_cod_malla` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`asignatura_id`, `requisito_cod_malla`),
  INDEX `fk_asignatura_has_requisito_requisito1_idx` (`asignatura_id` ASC),
  INDEX `fk_asignatura_has_requisito_asignatura1_idx` (`requisito_cod_malla` ASC),
  CONSTRAINT `fk_asignatura_has_requisito_asignatura1`
    FOREIGN KEY (`asignatura_id`)
    REFERENCES `tallerapp`.`asignatura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignatura_has_requisito_requisito1`
    FOREIGN KEY (`requisito_cod_malla`)
    REFERENCES `tallerapp`.`requisito` (`cod_malla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tallerapp`.`mencion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallerapp`.`mencion` (
  `idMencion` VARCHAR(3) NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `descrip` TEXT NOT NULL,
  `malla_idMalla` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`idMencion`),
  INDEX `fk_mencion_malla1_idx` (`malla_idMalla` ASC),
  CONSTRAINT `fk_mencion_malla1`
    FOREIGN KEY (`malla_idMalla`)
    REFERENCES `tallerapp`.`malla` (`idMalla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tallerapp`.`asig_mencion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallerapp`.`asig_mencion` (
  `profesor` VARCHAR(100) NOT NULL,
  `descripcion_corta` TEXT NOT NULL,
  `descripcion_larga` LONGTEXT NOT NULL,
  `url_imagen` VARCHAR(200) NOT NULL,
  `mencion_idMencion` VARCHAR(3) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `idCodigo` VARCHAR(6) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `academico_idacademico` INT NOT NULL,
  PRIMARY KEY (`nombre`),
  INDEX `fk_asig_mencion_mencion1_idx` (`mencion_idMencion` ASC),
  INDEX `fk_asig_mencion_academico1_idx` (`academico_idacademico` ASC),
  CONSTRAINT `fk_asig_mencion_mencion1`
    FOREIGN KEY (`mencion_idMencion`)
    REFERENCES `tallerapp`.`mencion` (`idMencion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asig_mencion_academico1`
    FOREIGN KEY (`academico_idacademico`)
    REFERENCES `mydb`.`academico` (`idacademico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tallerapp`.`descargas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallerapp`.`descargas` (
  `idDescargas` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(200) NOT NULL,
  `url` VARCHAR(300) NOT NULL,
  `abstract` TEXT NULL DEFAULT NULL,
  `anio` INT(4) NOT NULL,
  `estado` INT(11) NOT NULL,
  `idCodigo` VARCHAR(6) NOT NULL,
  `autor` VARCHAR(100) NULL DEFAULT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idDescargas`))
ENGINE = InnoDB
AUTO_INCREMENT = 60
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tallerapp`.`malla_has_semestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallerapp`.`malla_has_semestre` (
  `malla_idMalla` VARCHAR(3) NOT NULL,
  `semestre_semestre` INT(2) NOT NULL,
  PRIMARY KEY (`malla_idMalla`, `semestre_semestre`),
  INDEX `fk_malla_has_semestre_semestre1_idx` (`semestre_semestre` ASC),
  INDEX `fk_malla_has_semestre_malla1_idx` (`malla_idMalla` ASC),
  CONSTRAINT `fk_malla_has_semestre_malla1`
    FOREIGN KEY (`malla_idMalla`)
    REFERENCES `tallerapp`.`malla` (`idMalla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_malla_has_semestre_semestre1`
    FOREIGN KEY (`semestre_semestre`)
    REFERENCES `tallerapp`.`semestre` (`semestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tallerapp`.`usuario_administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallerapp`.`usuario_administrador` (
  `rut` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(20) NOT NULL,
  `mail` VARCHAR(50) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `nickname` VARCHAR(30) NOT NULL,
  `tipo` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`rut`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
